edition = "2021"
fn_single_line = true
format_macro_matchers = true
format_macro_bodies = false
format_strings = true
inline_attribute_width = 120
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
